CHANGELOG.md
source/lambda/util/logger.py

Updated to v1.4.1

---

.viperlightignore

reset viperlight ignores

---

buildspec.yml

this is necessary for the deployment step of the internal pipeline

create necessary open-source folder in pipeline

---

README.md

Adding guidance for how customers can test the solution after the new updates.

Update README documentation for testing the solution

---

.github/workflows/codeql-workflow.yml

Add a CodeQL security scan to the git workflow for all pushes/PRs

add CodeQL security scan workflow

---

source/infrastructure/package-lock.json
source/infrastructure/package.json
source/infrastructure/tests/aws-instance-scheduler-remote-stack.test.ts
source/infrastructure/tests/aws-instance-scheduler-stack.test.ts
source/infrastructure/tests/instance-scheduler-stack-factory.ts

migrating to the new libraries for cdk assertions.

migrate from @aws-cdk/assert to aws-cdk-lib/assertions

---

.github/workflows/build-workflow.yml
.github/workflows/cdk-nag-workflow.yml
.github/workflows/codeql-workflow.yml
.github/workflows/pipeline-workflow.yml
.github/workflows/pull-request-workflow.yml
.github/workflows/unit-test-workflow.yml
.github/workflows/viperlight-workflow.yml

Update the names of github workflows to make it clearer what they are doing

Update workflow names

---

deployment/cdk-solution-helper/README.md
deployment/cdk-solution-helper/asset-packager/__tests__/asset-packager.test.ts
deployment/cdk-solution-helper/asset-packager/__tests__/handler.test.ts
deployment/cdk-solution-helper/asset-packager/asset-packager.ts
deployment/cdk-solution-helper/asset-packager/index.ts
deployment/cdk-solution-helper/jest.config.ts
deployment/cdk-solution-helper/package-lock.json
deployment/cdk-solution-helper/package.json
deployment/cdk-solution-helper/tsconfig.json
source/infrastructure/bin/aws-instance-scheduler.ts
source/infrastructure/lib/aws-instance-scheduler-remote-stack.ts
source/infrastructure/lib/aws-instance-scheduler-stack.ts
source/infrastructure/lib/core-scheduler.ts
source/infrastructure/pipeline/pipeline-stack.ts

testing against internal pipeline

setup CDK-Helper

---

source/infrastructure/jest.config.ts
source/infrastructure/lib/__snapshots__/core-scheduler.test.ts.snap
source/infrastructure/lib/core-scheduler.test.ts

- add fine-grained cdk tests for core scheduler
Ideological question: do these tests add value? Or are they a waste of time?

Add tests for core scheduler

---

buildspec.yml
deployment/build-s3-dist.sh

build updates

---

README.md

This is a followup PR to the end-to-end testing. The only relevant changes are to the readme as the rest are from  https://github.com/aws-solutions/aws-instance-scheduler/pull/410.

Update README deployment instructions

---

source/app/tests/configuration/test_configuration.py

- add tests for configuration __init__

Add tests for configuration __init__

---

source/cli/poetry.lock
source/cli/pyproject.toml

include pytest-cov in cli dev dependencies

---

deployment/run-unit-tests.sh

sonarqube fixes

---

source/infrastructure/instance-scheduler/lib/aws-instance-scheduler-stack.ts
source/infrastructure/instance-scheduler/tests/__snapshots__/aws-instance-scheduler-stack.test.ts.snap

update CloudWatch Logs CFN parameter name to CloudWatch Debug Logs

---

source/infrastructure/instance-scheduler/lib/core-scheduler.ts
source/infrastructure/instance-scheduler/tests/lib/core-scheduler.test.ts

remove unused S3 reference

---

README.md

Update readme with new deployment instructions

---

README.md

CHORE: Readme updates

---

sonar-project.properties

CHORE: set sonarqube python version to 3.9

---

CHANGELOG.md

* Updating changelog.md for v1.5.0

Updating changelog.md for v1.5.0 (#451)
